import Head from 'next/head'
import Link from 'next/link';
import React, {Component} from 'react';
import { gql } from "@apollo/client";
import client from "../../apollo-client";
import Layout from '../../components/layout'
import LibCookie from '../../lib/LibCookie'
import IndexRow from './IndexRow';
// 
export default class NoteIndex extends Component {
  static async getInitialProps(ctx) {
    const data = await client.query({
      query: gql`
      query {
        notes {
          id
          title
          content
          noteTag{
            id
            name
          }
        }
      }
      `,
      fetchPolicy: "network-only"
    });
console.log(data);   
    return {
      items: data,
    }
  }  
  constructor(props){
    super(props)
  }
  componentDidMount(){
    const key = process.env.COOKIE_KEY_USER_ID;
    if(LibCookie.get_cookie(key) === null){
      location.href = '/login';
    }
  }
  render() {
    const data = this.props;
console.log(data.items.data.notes);
    const items = data.items.data.notes;
    return (
    <Layout>
      <Head><meta name="description" content="Generated by create next app" />
      </Head>
      <div className="container">
        <Link href="/notes/create">
          <a className="btn btn-primary mt-2">New</a>
        </Link>      
        <div>
          <h3>Notes - index</h3>
          <hr />
          {items.map((item ,index) => {
            return (
              <IndexRow key={index} id={item.id} title={item.title} />
            )
          })}        
          </div>
      </div>
    </Layout>
    )
  }   
}

